package com.spiffymap.datalog.ui.mvp.history;

import com.spiffymap.server.ui.UIUtils;
import java.awt.Frame;
import javax.swing.JDialog;
import net.spiffymap.datalog.shared.mvp.history.EditHistoryPresenter;
import net.spiffymap.datalog.shared.mvp.history.EditHistoryView;

/**
 *
 * @author steve
 */
public class EditHistoryDialog extends JDialog implements EditHistoryView {

    private EditHistoryPresenter presenter;

    /**
     * Creates new form EditHistoryDialog
     *
     * @param parent
     */
    public EditHistoryDialog(Frame parent) {
        super(parent, false);
        initComponents();
        setSize(1000, 500);
        UIUtils.centreOnScreen(EditHistoryDialog.this);
    }

    @Override
    public void refresh() {
        EditHistoryTableModel model = new EditHistoryTableModel();
        model.setEditHistoryItems(presenter.getEditHistory().getHistory());
        editHistoryTable.setModel(model);
        model.fireTableDataChanged();
    }

    @Override
    public void showView() {
        refresh();
        setVisible(true);
    }

    @Override
    public void hideView() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        editHistoryTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit history");
        setAlwaysOnTop(true);

        editHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(editHistoryTable);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });
        topPanel.add(undoButton);

        redoButton.setText("Redo");
        redoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoButtonActionPerformed(evt);
            }
        });
        topPanel.add(redoButton);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        hideView();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        presenter.undo();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoButtonActionPerformed
        presenter.redo();
    }//GEN-LAST:event_redoButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JTable editHistoryTable;
    private javax.swing.JButton redoButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @param presenter the presenter to set
     */
    @Override
    public void setPresenter(EditHistoryPresenter presenter) {
        this.presenter = presenter;
    }
}
