package com.spiffymap.datalog.ui.mvp.details;

import javax.swing.JList;
import javax.swing.JPanel;
import net.spiffymap.datalog.client.model.DatalogFile;
import net.spiffymap.datalog.shared.mvp.details.DetailCoordinatePresenter;
import net.spiffymap.datalog.shared.mvp.details.DetailCoordinateView;

/**
 *
 * @author steve
 */
public class DetailCoordinatePanel extends JPanel implements SwingDetailList, DetailCoordinateView {

    private DetailCoordinatePresenter presenter;
    private final DetailCoordinateListModel listModel = new DetailCoordinateListModel();

    /**
     * Creates new form DetailCoordinatePanel
     */
    public DetailCoordinatePanel() {
        initComponents();
    }

    @Override
    public void showView() {

    }

    @Override
    public void hideView() {
        // No action needed
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailCoordinateLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        coordinatesList = new javax.swing.JList<>();

        setLayout(new java.awt.BorderLayout());

        detailCoordinateLabel.setText("jLabel1");
        add(detailCoordinateLabel, java.awt.BorderLayout.PAGE_START);

        coordinatesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPane.setViewportView(coordinatesList);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> coordinatesList;
    private javax.swing.JLabel detailCoordinateLabel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    /**
     * @param presenter the presenter to set
     */
    @Override
    public void setPresenter(DetailCoordinatePresenter presenter) {
        this.presenter = presenter;
    }

    /**
     * Pass on to the presenter the name of the component it's handling
     *
     * @param name
     */
    @Override
    public void setComponentName(String name) {
        presenter.setComponentName(name);
    }

    /**
     * @return the presenter
     */
    @Override
    public DetailCoordinatePresenter getPresenter() {
        return presenter;
    }

    @Override
    public void refresh() {
    }

    @Override
    public JList getList() {
        return coordinatesList;
    }

    /**
     * @return the tableModel
     */
    @Override
    public DetailCoordinateListModel getListModel() {
        return listModel;
    }

    @Override
    public DatalogFile getFile() {
        return presenter.getFile();
    }
}
