package com.spiffymap.datalog.ui.mvp.problems;

import com.spiffymap.server.ui.UIUtils;
import java.awt.Frame;
import javax.swing.JDialog;
import net.spiffymap.datalog.shared.mvp.problems.DXFCompletePresenter;
import net.spiffymap.datalog.shared.mvp.problems.DXFCompleteView;

/**
 *
 * @author steve
 */
public class DXFCompleteDialog extends JDialog implements DXFCompleteView {

    private DXFCompletePresenter presenter;

    /**
     * Creates new form DXFCompleteDialog
     *
     * @param parent
     */
    public DXFCompleteDialog(Frame parent) {
        super(parent, true);
        initComponents();
        pack();
        UIUtils.centreOnScreen(DXFCompleteDialog.this);
    }

    @Override
    public void showView() {
        setVisible(true);
    }

    @Override
    public void hideView() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        reportButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        centrePanel = new javax.swing.JPanel();
        messageDisplayLabel1 = new javax.swing.JLabel();
        messageDisplayLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        reportButton.setText("Report problem with DXF");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(reportButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        messageDisplayLabel1.setText("Please leave this dialog open while you load the DXF file into CAD.");

        messageDisplayLabel2.setText("If there is a problem, click \"Report problem with DXF\", otherwise click \"Close\".");

        javax.swing.GroupLayout centrePanelLayout = new javax.swing.GroupLayout(centrePanel);
        centrePanel.setLayout(centrePanelLayout);
        centrePanelLayout.setHorizontalGroup(
            centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centrePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageDisplayLabel1)
                    .addComponent(messageDisplayLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        centrePanelLayout.setVerticalGroup(
            centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centrePanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(messageDisplayLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageDisplayLabel2)
                .addGap(28, 28, 28))
        );

        getContentPane().add(centrePanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        presenter.reportProblem();
        hideView();
    }//GEN-LAST:event_reportButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        hideView();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel centrePanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel messageDisplayLabel1;
    private javax.swing.JLabel messageDisplayLabel2;
    private javax.swing.JButton reportButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @param presenter the presenter to set
     */
    @Override
    public void setPresenter(DXFCompletePresenter presenter) {
        this.presenter = presenter;
    }
}
