package com.spiffymap.datalog.ui.mvp.stations;

import net.spiffymap.datalog.shared.mvp.ValidatingDialog;
import com.spiffymap.server.ui.UIUtils;
import java.awt.Frame;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;
import net.spiffymap.datalog.client.model.DataType;
import net.spiffymap.datalog.client.model.validators.AcceptanceValidator;
import net.spiffymap.datalog.client.model.validators.ValidationLink;
import com.spiffymap.geo.shared.TextComponentWrapper;
import com.spiffymap.gui.swing.SwingTextComponentWrapperFactory;
import net.spiffymap.datalog.shared.mvp.stations.StationInputView;
import com.spiffymap.mvp.shared.ui.Dialogs;

/**
 *
 * @author steve
 */
public class StationInputDialog extends JDialog implements StationInputView, ValidatingDialog {

    private Runnable runIfAccepted;
    private AcceptanceValidator acceptanceValidator;
    private final SwingTextComponentWrapperFactory wrapperFactory = new SwingTextComponentWrapperFactory();
    private boolean accepted;
    private final Map<TextComponentWrapper, ValidationLink> validationMap = new HashMap<>();
    private Dialogs dialogs;

    /**
     * Creates new form StationInputDialog
     *
     * @param parent
     * @param dialogs
     */
    public StationInputDialog(Frame parent, Dialogs dialogs) {
        super(parent, true);
        this.dialogs = dialogs;
        initComponents();
        setupValidation();
        UIUtils.centreOnScreen(StationInputDialog.this);
        setSize(800, 400);
    }

    private void setValidationLinkForField(JTextField field, DataType dataType, JLabel validationLabel) {
        setValidationLink(wrapperFactory.wrap(field), dataType, wrapperFactory.wrap(validationLabel));
    }

    protected void setupValidation() {
        setValidationLinkForField(numberField, DataType.STRING, numberValidationLabel);
        setValidationLinkForField(roField, DataType.STRING, roValidationLabel);
        setValidationLinkForField(eastingField, DataType.COORDINATE, eastingValidationLabel);
        setValidationLinkForField(northingField, DataType.COORDINATE, northingValidationLabel);
        setValidationLinkForField(levelField, DataType.DOUBLE, levelValidationLabel);
        setValidationLinkForField(instrumentHeightField, DataType.DOUBLE, instrumentHeightValidationLabel);
    }

    @Override
    public void showAndWait(Runnable runIfAccepted) {
        this.runIfAccepted = runIfAccepted;
        clearAllValues();
        setVisible(true);
    }

    @Override
    public void hideView() {
        setVisible(false);
    }

    @Override
    public Runnable getRunIfAccepted() {
        return runIfAccepted;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        centrePanel = new javax.swing.JPanel();
        numberLabel = new javax.swing.JLabel();
        numberField = new javax.swing.JTextField();
        roLabel = new javax.swing.JLabel();
        roField = new javax.swing.JTextField();
        eastingLabel = new javax.swing.JLabel();
        eastingField = new javax.swing.JTextField();
        northingLabel = new javax.swing.JLabel();
        northingField = new javax.swing.JTextField();
        levelLabel = new javax.swing.JLabel();
        levelField = new javax.swing.JTextField();
        instrumentHeightLabel = new javax.swing.JLabel();
        instrumentHeightField = new javax.swing.JTextField();
        eastingValidationLabel = new javax.swing.JLabel();
        northingValidationLabel = new javax.swing.JLabel();
        levelValidationLabel = new javax.swing.JLabel();
        instrumentHeightValidationLabel = new javax.swing.JLabel();
        numberValidationLabel = new javax.swing.JLabel();
        roValidationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input station");

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        acceptButton.setText("Accept");
        acceptButton.setName("acceptButton"); // NOI18N
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(acceptButton);

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberLabel.setText("Number");

        numberField.setName("numberField"); // NOI18N
        numberField.setPreferredSize(new java.awt.Dimension(100, 24));

        roLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roLabel.setText("R.O.");

        roField.setName("roField"); // NOI18N
        roField.setPreferredSize(new java.awt.Dimension(100, 24));

        eastingLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eastingLabel.setText("Easting");

        eastingField.setName("eastingField"); // NOI18N
        eastingField.setPreferredSize(new java.awt.Dimension(200, 24));

        northingLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        northingLabel.setText("Northing");

        northingField.setName("northingField"); // NOI18N
        northingField.setPreferredSize(new java.awt.Dimension(200, 24));

        levelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        levelLabel.setText("Level");

        levelField.setName("levelField"); // NOI18N
        levelField.setPreferredSize(new java.awt.Dimension(200, 24));
        levelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelFieldActionPerformed(evt);
            }
        });

        instrumentHeightLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        instrumentHeightLabel.setText("Instrument height");

        instrumentHeightField.setName("instrumentHeightField"); // NOI18N
        instrumentHeightField.setPreferredSize(new java.awt.Dimension(200, 24));

        eastingValidationLabel.setName(""); // NOI18N
        eastingValidationLabel.setPreferredSize(new java.awt.Dimension(129, 22));

        northingValidationLabel.setPreferredSize(new java.awt.Dimension(129, 22));

        levelValidationLabel.setPreferredSize(new java.awt.Dimension(129, 22));

        instrumentHeightValidationLabel.setPreferredSize(new java.awt.Dimension(129, 22));

        numberValidationLabel.setName("numberValidation"); // NOI18N
        numberValidationLabel.setPreferredSize(new java.awt.Dimension(129, 22));

        roValidationLabel.setPreferredSize(new java.awt.Dimension(129, 22));

        javax.swing.GroupLayout centrePanelLayout = new javax.swing.GroupLayout(centrePanel);
        centrePanel.setLayout(centrePanelLayout);
        centrePanelLayout.setHorizontalGroup(
            centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centrePanelLayout.createSequentialGroup()
                .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centrePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instrumentHeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centrePanelLayout.createSequentialGroup()
                        .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(northingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eastingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centrePanelLayout.createSequentialGroup()
                        .addComponent(instrumentHeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instrumentHeightValidationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(centrePanelLayout.createSequentialGroup()
                        .addComponent(eastingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eastingValidationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(centrePanelLayout.createSequentialGroup()
                        .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(centrePanelLayout.createSequentialGroup()
                                .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(levelValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(centrePanelLayout.createSequentialGroup()
                                .addComponent(roField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(centrePanelLayout.createSequentialGroup()
                                .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(centrePanelLayout.createSequentialGroup()
                                .addComponent(northingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(northingValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        centrePanelLayout.setVerticalGroup(
            centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centrePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(centrePanelLayout.createSequentialGroup()
                        .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberLabel))
                        .addGap(1, 1, 1)))
                .addGap(10, 10, 10)
                .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(centrePanelLayout.createSequentialGroup()
                        .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roLabel))
                        .addGap(1, 1, 1))
                    .addComponent(roValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(centrePanelLayout.createSequentialGroup()
                        .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eastingValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(eastingLabel)
                                .addComponent(eastingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(northingLabel)
                            .addComponent(northingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(northingValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centrePanelLayout.createSequentialGroup()
                        .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(levelLabel)
                                .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(levelValidationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instrumentHeightLabel)
                            .addComponent(instrumentHeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(instrumentHeightValidationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(centrePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        acceptAction();
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelAction();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void levelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centrePanel;
    private javax.swing.JTextField eastingField;
    private javax.swing.JLabel eastingLabel;
    private javax.swing.JLabel eastingValidationLabel;
    private javax.swing.JTextField instrumentHeightField;
    private javax.swing.JLabel instrumentHeightLabel;
    private javax.swing.JLabel instrumentHeightValidationLabel;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel levelValidationLabel;
    private javax.swing.JTextField northingField;
    private javax.swing.JLabel northingLabel;
    private javax.swing.JLabel northingValidationLabel;
    private javax.swing.JTextField numberField;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel numberValidationLabel;
    private javax.swing.JTextField roField;
    private javax.swing.JLabel roLabel;
    private javax.swing.JLabel roValidationLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the acceptanceValidator
     */
    @Override
    public AcceptanceValidator getAcceptanceValidator() {
        return acceptanceValidator;
    }

    /**
     * @param acceptanceValidator the acceptanceValidator to set
     */
    @Override
    public void setAcceptanceValidator(AcceptanceValidator acceptanceValidator) {
        this.acceptanceValidator = acceptanceValidator;
    }

    /**
     * @return the accepted
     */
    @Override
    public boolean isAccepted() {
        return accepted;
    }

    /**
     * @param accepted the accepted to set
     */
    @Override
    public void setAccepted(boolean accepted) {
        this.accepted = accepted;
    }

    /**
     * @return the validationMap
     */
    @Override
    public Map<TextComponentWrapper, ValidationLink> getValidationMap() {
        return validationMap;
    }

    @Override
    public void showMessage(String message, String title) {
        dialogs.showMessageDialog(message, title);
    }

    @Override
    public void cancelAction() {
        accepted = false;
        setVisible(false);
    }
}
