package com.spiffymap.datalog.ui.mvp.stations;

import com.spiffymap.server.ui.UIUtils;
import java.awt.Frame;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import net.spiffymap.datalog.client.model.Traverse;
import net.spiffymap.datalog.shared.mvp.stations.TraverseInputView;

/**
 *
 * @author steve
 */
public class TraverseInputDialog extends JDialog implements TraverseInputView {

    private Traverse traverse;
    private boolean accepted;

    /**
     * Creates new form TraverseInputDialog
     *
     * @param parent
     */
    public TraverseInputDialog(Frame parent) {
        super(parent, true);
        initComponents();
        UIUtils.centreOnScreen(TraverseInputDialog.this);
    }

    @Override
    public void showView(List<String> stationNumbers) {
        DefaultComboBoxModel startModel = new DefaultComboBoxModel(stationNumbers.toArray(new String[]{}));
        DefaultComboBoxModel endModel = new DefaultComboBoxModel(stationNumbers.toArray(new String[]{}));
        startCombo.setModel(startModel);
        endCombo.setModel(endModel);
        showView();
    }

    @Override
    public void showView() {
        traverse = null;
        accepted = false;
        setVisible(true);
    }

    @Override
    public void hideView() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        startCombo = new javax.swing.JComboBox<>();
        endLabel = new javax.swing.JLabel();
        endCombo = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setTitle("New traverse");
        setModal(true);
        setResizable(false);

        startLabel.setText("Start station:");

        startCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        endLabel.setText("End station:");

        endCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startLabel)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(endLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLabel)
                    .addComponent(startCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLabel)
                    .addComponent(endCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.LINE_START);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(acceptButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        accepted = true;
        setVisible(false);
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        accepted = false;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> endCombo;
    private javax.swing.JLabel endLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> startCombo;
    private javax.swing.JLabel startLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the traverse
     */
    @Override
    public Traverse getTraverse() {
        if (accepted) {
            String start = (String) startCombo.getSelectedItem();
            String end = (String) endCombo.getSelectedItem();
            traverse = new Traverse(start, end);
        } else {
            traverse = null;
        }
        return traverse;
    }

    /**
     * @return the accepted
     */
    @Override
    public boolean isAccepted() {
        return accepted;
    }
}
