package com.spiffymap.datalog.ui.mvp.information;

import com.spiffymap.server.ui.UIUtils;
import java.awt.Frame;
import java.util.List;
import javax.swing.JDialog;
import net.spiffymap.datalog.shared.mvp.information.CodesPresenter;
import net.spiffymap.datalog.shared.mvp.information.CodesView;

/**
 *
 * @author steve
 */
public class CodesDialog extends JDialog implements CodesView {

    private CodesPresenter presenter;
    private String[] codesArray;

    /**
     * Creates new form CodesDialog
     *
     * @param parent
     */
    public CodesDialog(Frame parent) {
        super(parent, true);
        initComponents();
        UIUtils.centreOnScreen(CodesDialog.this);
    }

    @Override
    public void showView() {
        setVisible(true);
    }

    @Override
    public void hideView() {
        setVisible(false);
    }

    @Override
    public void setCodes(List<String> codes) {
        codesArray = codes.toArray(new String[]{});
        codesList.setListData(codesArray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeListLabel = new javax.swing.JLabel();
        codesListScrollPane = new javax.swing.JScrollPane();
        codesList = new javax.swing.JList<>();
        descriptionLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextPane();
        aCodeLabel = new javax.swing.JLabel();
        bCodeLabel = new javax.swing.JLabel();
        aCodeUseText = new javax.swing.JTextField();
        bCodeUseText = new javax.swing.JTextField();
        parallelCheckBox = new javax.swing.JCheckBox();
        labelLabel = new javax.swing.JLabel();
        labelField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Codes");
        setResizable(false);

        codeListLabel.setText("Code");

        codesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        codesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                codesListValueChanged(evt);
            }
        });
        codesListScrollPane.setViewportView(codesList);

        descriptionLabel.setText("Description");

        descriptionText.setEditable(false);
        descriptionScrollPane.setViewportView(descriptionText);

        aCodeLabel.setText("A Code use");

        bCodeLabel.setText("B Code use");

        aCodeUseText.setEditable(false);

        bCodeUseText.setEditable(false);

        parallelCheckBox.setText("Parallel possible");
        parallelCheckBox.setEnabled(false);

        labelLabel.setText("Label");

        labelField.setEditable(false);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codesListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(aCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(labelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(descriptionScrollPane)
                                .addComponent(aCodeUseText, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                            .addComponent(labelField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(closeButton))
                            .addComponent(bCodeUseText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parallelCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(codeListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codeListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codesListScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionLabel)
                            .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aCodeLabel)
                            .addComponent(aCodeUseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bCodeLabel)
                            .addComponent(bCodeUseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(parallelCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_codesListValueChanged
        String selectedCode = codesList.getSelectedValue();
        if(selectedCode != null) {
            presenter.selectCode(selectedCode);
        }
    }//GEN-LAST:event_codesListValueChanged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aCodeLabel;
    private javax.swing.JTextField aCodeUseText;
    private javax.swing.JLabel bCodeLabel;
    private javax.swing.JTextField bCodeUseText;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel codeListLabel;
    private javax.swing.JList<String> codesList;
    private javax.swing.JScrollPane codesListScrollPane;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextPane descriptionText;
    private javax.swing.JTextField labelField;
    private javax.swing.JLabel labelLabel;
    private javax.swing.JCheckBox parallelCheckBox;
    // End of variables declaration//GEN-END:variables

    /**
     * @param presenter the presenter to set
     */
    @Override
    public void setPresenter(CodesPresenter presenter) {
        this.presenter = presenter;
    }

    @Override
    public void setDescription(String description) {
        descriptionText.setText(description);
    }

    @Override
    public void setACodeUse(String aCodeUse) {
        aCodeUseText.setText(aCodeUse);
    }

    @Override
    public void setBCodeUse(String bCodeUse) {
        bCodeUseText.setText(bCodeUse);
    }

    @Override
    public void setParallel(boolean parallel) {
        parallelCheckBox.setSelected(parallel);
    }

    @Override
    public void setLabel(String label) {
        labelField.setText(label);
    }
}
