package com.spiffymap.datalog.ui.mvp.information;

import java.util.Arrays;
import javax.swing.JPanel;
import net.spiffymap.datalog.shared.mvp.information.InformationPresenter;
import net.spiffymap.datalog.shared.mvp.information.InformationView;

/**
 *
 * @author steve
 */
public class InformationPanel extends JPanel implements InformationView {

    private InformationPresenter presenter;

    /**
     * Creates new form InformationPanel
     */
    public InformationPanel() {
        initComponents();
        // Initially disable controls

    }

    @Override
    public void enableControls(boolean enable) {
        Arrays.asList(editDetailsButton, editStationsButton, newsButton).forEach(control -> control.setEnabled(enable));
    }

    @Override
    public void setFileName(String fileName) {
        fileText.setText(fileName);
    }

    @Override
    public void setStationsCount(int stationsCount) {
        stationsText.setText(String.valueOf(stationsCount));
    }

    @Override
    public void setDetailsCount(int detailsCount) {
        detailsText.setText(String.valueOf(detailsCount));
    }

    @Override
    public void showView() {
        setVisible(true);
    }

    @Override
    public void hideView() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileLabel = new javax.swing.JLabel();
        stationsLabel = new javax.swing.JLabel();
        detailsLabel = new javax.swing.JLabel();
        fillerY = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerX = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        editDetailsButton = new javax.swing.JButton();
        editStationsButton = new javax.swing.JButton();
        fileText = new javax.swing.JLabel();
        stationsText = new javax.swing.JLabel();
        detailsText = new javax.swing.JLabel();
        newsButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        fileLabel.setText("File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(fileLabel, gridBagConstraints);

        stationsLabel.setText("Stations:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(stationsLabel, gridBagConstraints);

        detailsLabel.setText("Details:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(detailsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weighty = 1.0;
        add(fillerY, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        add(fillerX, gridBagConstraints);

        editDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/details.png"))); // NOI18N
        editDetailsButton.setText("Edit details ....");
        editDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDetailsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(editDetailsButton, gridBagConstraints);

        editStationsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stations.png"))); // NOI18N
        editStationsButton.setText("Edit stations ....");
        editStationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStationsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(editStationsButton, gridBagConstraints);
        editStationsButton.getAccessibleContext().setAccessibleDescription("");

        fileText.setPreferredSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(fileText, gridBagConstraints);

        stationsText.setPreferredSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(stationsText, gridBagConstraints);

        detailsText.setPreferredSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(detailsText, gridBagConstraints);

        newsButton.setText("News");
        newsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(newsButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void editDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDetailsButtonActionPerformed
        presenter.editDetails();
    }//GEN-LAST:event_editDetailsButtonActionPerformed

    private void editStationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStationsButtonActionPerformed
        presenter.editStations();
    }//GEN-LAST:event_editStationsButtonActionPerformed

    private void newsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsButtonActionPerformed
        presenter.showNews();
    }//GEN-LAST:event_newsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JLabel detailsText;
    private javax.swing.JButton editDetailsButton;
    private javax.swing.JButton editStationsButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel fileText;
    private javax.swing.Box.Filler fillerX;
    private javax.swing.Box.Filler fillerY;
    private javax.swing.JButton newsButton;
    private javax.swing.JLabel stationsLabel;
    private javax.swing.JLabel stationsText;
    // End of variables declaration//GEN-END:variables

    /**
     * @param presenter the presenter to set
     */
    @Override
    public void setPresenter(InformationPresenter presenter) {
        this.presenter = presenter;
    }
}
