package com.spiffymap.datalog.ui.mvp.logo;

import com.spiffymap.datalog.ui.mvp.ImageAnimator;
import javax.swing.JPanel;
import net.spiffymap.datalog.shared.mvp.logo.LogoView;
import net.spiffymap.datalog.shared.mvp.main.DatalogPresenter;

/**
 *
 * @author steve
 */
public class LogoPanel extends JPanel implements LogoView {

    private DatalogPresenter presenter;

    /**
     * Creates new form LogoPanel
     */
    public LogoPanel() {
        initComponents();
        datalogText.setText("Datalog X");
        //startAnimation();
    }

    private void startAnimation() {
        ImageAnimator animator = new ImageAnimator();
        animator.animate(iconButton, "/resources/goto.png", "/resources/logo_1.png",
                "/resources/logo_2.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        iconButton = new javax.swing.JButton();
        datalogText = new javax.swing.JLabel();
        newsButton = new javax.swing.JButton();
        latestNewsLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png"))); // NOI18N
        iconButton.setBorder(null);
        iconButton.setPreferredSize(new java.awt.Dimension(140, 140));
        add(iconButton, new java.awt.GridBagConstraints());

        datalogText.setFont(new java.awt.Font("LM Roman Dunhill 10", 0, 24)); // NOI18N
        datalogText.setText("Datalog X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(datalogText, gridBagConstraints);

        newsButton.setText("News");
        newsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        add(newsButton, gridBagConstraints);

        latestNewsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        latestNewsLabel.setText("Latest feature: Report Problems");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        add(latestNewsLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void newsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsButtonActionPerformed
        presenter.showNews();
    }//GEN-LAST:event_newsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datalogText;
    private javax.swing.JButton iconButton;
    private javax.swing.JLabel latestNewsLabel;
    private javax.swing.JButton newsButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @param presenter the presenter to set
     */
    @Override
    public void setPresenter(DatalogPresenter presenter) {
        this.presenter = presenter;
    }
}
