package com.spiffymap.datalog.ui.mvp;

import java.awt.Frame;
import java.awt.Rectangle;
import java.io.StringReader;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author steve
 */
public class EditGuideDialog extends javax.swing.JDialog {

    private Rectangle bounds;

    /**
     * Creates new form EditGuideDialog
     *
     * @param parent
     */
    public EditGuideDialog(Frame parent) {
        super(parent, false);
        initComponents();
        helpPane.setEditorKit(new HTMLEditorKit());
    }

    public void setHelpText(String text) {
        helpPane.setText(text);
    }

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            if (bounds == null) {
                pack();
                int width = getWidth();
                int height = getHeight();
                int parentWidth = getParent().getWidth();
                int left = getParent().getX() + parentWidth - width - 10;
                int top = getParent().getY() + 50;
                bounds = new Rectangle(left, top, width, height);
                setBounds(bounds);
            }
        }
        super.setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpScroll = new javax.swing.JScrollPane();
        helpPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guide");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        helpPane.setEditable(false);
        helpPane.setPreferredSize(new java.awt.Dimension(150, 400));
        helpScroll.setViewportView(helpPane);

        getContentPane().add(helpScroll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        bounds = null;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGuideDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGuideDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGuideDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGuideDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane helpPane;
    private javax.swing.JScrollPane helpScroll;
    // End of variables declaration//GEN-END:variables
}
