package com.spiffymap.datalog.client.mvp.help;

import com.spiffymap.server.ui.UIUtils;
import java.awt.Frame;
import javax.swing.JDialog;
import net.spiffymap.datalog.client.mvp.help.HelpView;

/**
 *
 * @author steve
 */
public class HelpDialog extends JDialog implements HelpView {

    /**
     * Creates new form HelpDialog
     *
     * @param parent
     */
    public HelpDialog(Frame parent) {
        super(parent, false);
        initComponents();
        setSize(600, 600);
        UIUtils.centreOnScreen(HelpDialog.this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();

        editorPane.setEditable(false);
        editorPane.setContentType("text/html"); // NOI18N
        scrollPane.setViewportView(editorPane);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void showView() {
        throw new IllegalArgumentException("Should be supplied with help text");
    }

    @Override
    public void showView(String text) {
        editorPane.setText(text);
        setVisible(true);
    }

    @Override
    public void hideView() {
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
